### ISSUE TITLE
Crash after placing the paint

### ISSUE THREAD

**Issue by Karakownia** [Flenix/FlenixRoads#13]
```
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:235)
	at com.silvaniastudios.roads.blocks.paint.FarSideLinePaintBlock.func_176203_a(FarSideLinePaintBlock.java:57)
	at mods.railcraft.common.util.inventory.InvTools.getBlockStateFromStack(InvTools.java:488)
	at mods.railcraft.common.blocks.tracks.TrackTools.isRailBlock(TrackTools.java:73)
	at mods.railcraft.common.advancements.criterion.TrackItemPredicate.func_192493_a(TrackItemPredicate.java:66)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger$Instance.func_192265_a(SourceFile:104)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger$Listeners.func_192486_a(SourceFile:149)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.func_192208_a(SourceFile:69)
	at net.minecraft.entity.player.EntityPlayerMP.func_71111_a(EntityPlayerMP.java:972)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:91)
	at net.minecraft.inventory.Container.func_75132_a(Container.java:53)
	at net.minecraft.entity.player.EntityPlayerMP.func_71116_b(EntityPlayerMP.java:289)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@d86f3c2
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1614369136 bytes (1539 MB) / 7572291584 bytes (7221 MB) up to 7572291584 bytes (7221 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx8064m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2816 Optifine OptiFine_1.12.2_HD_U_E3 112 mods loaded, 112 

```

**Comment by Fureniku** [comment]
Fixed in 1.1, coming soon
