### ISSUE TITLE
Errors spam when looking at 2 of the machines

### ISSUE THREAD

**Issue by freelancerleno** [Flenix/FlenixRoads#8]
Hi,
There is error spam when you look at the Tar Distiller and the Road Factory with the Hwyla mod.

[17:24:29] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at mcp.mobius.waila.addons.capability.HUDHandlerTank.getNBTData(HUDHandlerTank.java:61) ~[HUDHandlerTank.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:93) ~[MessageRequestTile$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

It says that but I'm on singleplayer world

So, I found similar errors on Hwyla's Github but it seems that this error does not concern them. For example: https://github.com/TehNut/HWYLA/issues/115
That's why I'm posting here.

Forge: 14.23.5.2836
Fureniku's Roads: 1.0.2.1
Hwyla: 1.8.26-B41_1.12.2
Tested with only this 2 mods to avoid any other conflict

**Comment by Fureniku** [comment]
Hmm... it's going to be hard to track down the exact problem as the stack doesn't point to my code but I'll see what I can find.

It's kind of a problem with both external mods and HWYLA really. HWYLA is throwing the actual error and they could _prevent_ it - but the error is being caused as a root problem in the other mods. At any rate I'll try and get it fixed for 1.1 :)

**Comment by freelancerleno** [comment]
Thanks, if you can't fix it, I'll open an issue at Hwyla by linking this post to see what they can do.

**Comment by Fureniku** [comment]
Apologies for the delay - this is fixed in 1.1 which has just been released on Curseforge (pending approval)
